# Amount of render samples used when rendering from source.
# A good tradeoff between speed and quality seems to be somewhere around 120.
render_samples := 20
# Threads used by Blender, 0 means systems processor count
# Experiment with make -j n
threads := 1
