#####################################
# VARIABLES
#####################################

SHELL := /bin/bash

.SUFFIXES:

_E := @echo
_V := @

#####################################

.PHONY: all clean

#include Makefile.config

BUILD := build
SRC := src

all:
	$(_E) "I just love \'em trains."
